// =============================================
// HRM ROLES - khớp với field hrmRole trong User
// =============================================
export enum Role {
    SUPER_ADMIN = "SUPER_ADMIN",
    DIRECTOR = "DIRECTOR",
    HR_MANAGER = "HR_MANAGER",
    HR_STAFF = "HR_STAFF",
    DEPT_MANAGER = "DEPT_MANAGER",
    TEAM_LEADER = "TEAM_LEADER",
    EMPLOYEE = "EMPLOYEE",
    ACCOUNTANT = "ACCOUNTANT",
    IT_ADMIN = "IT_ADMIN",
}

// =============================================
// PERMISSIONS
// =============================================
export enum Permission {
    // Dashboard
    DASHBOARD_VIEW = "dashboard:view",
    DASHBOARD_VIEW_ALL = "dashboard:view_all",

    // Sơ đồ tổ chức
    ORG_CHART_VIEW = "org_chart:view",
    ORG_CHART_EDIT = "org_chart:edit",

    // Phòng ban
    DEPT_VIEW = "department:view",
    DEPT_CREATE = "department:create",
    DEPT_EDIT = "department:edit",
    DEPT_DELETE = "department:delete",

    // Chức vụ
    POSITION_VIEW_ALL = "position:view_all",
    POSITION_CREATE = "position:create",
    POSITION_EDIT = "position:edit",
    POSITION_DELETE = "position:delete",

    // Nhân viên
    EMPLOYEE_VIEW_SELF = "employee:view_self",
    EMPLOYEE_VIEW_TEAM = "employee:view_team",
    EMPLOYEE_VIEW_ALL = "employee:view_all",
    EMPLOYEE_CREATE = "employee:create",
    EMPLOYEE_EDIT = "employee:edit",
    EMPLOYEE_DELETE = "employee:delete",
    EMPLOYEE_UPDATE = "employee:update",
    EMPLOYEE_IMPORT = "employee:import",
    EMPLOYEE_EXPORT = "employee:export",

    // Hợp đồng
    CONTRACT_VIEW_SELF = "contract:view_self",
    CONTRACT_VIEW_ALL = "contract:view_all",
    CONTRACT_CREATE = "contract:create",
    CONTRACT_EDIT = "contract:edit",
    CONTRACT_PRINT = "contract:print",
    CONTRACT_TEMPLATE_MANAGE = "contract:template_manage",

    // Nghỉ phép
    LEAVE_VIEW_SELF = "leave:view_self",
    LEAVE_VIEW_TEAM = "leave:view_team",
    LEAVE_VIEW_ALL = "leave:view_all",
    LEAVE_CREATE = "leave:create",
    LEAVE_APPROVE_TEAM = "leave:approve_team",
    LEAVE_APPROVE_ALL = "leave:approve_all",
    LEAVE_POLICY_MANAGE = "leave:policy_manage",
    LEAVE_CALENDAR_VIEW = "leave:calendar_view",

    // Chấm công
    ATTENDANCE_VIEW_SELF = "attendance:view_self",
    ATTENDANCE_VIEW_TEAM = "attendance:view_team",
    ATTENDANCE_VIEW_ALL = "attendance:view_all",
    ATTENDANCE_CHECKIN = "attendance:checkin",
    ATTENDANCE_EXPLANATION = "attendance:explanation",
    ATTENDANCE_APPROVE = "attendance:approve",
    ATTENDANCE_SHIFT_MANAGE = "attendance:shift_manage",
    ATTENDANCE_OVERTIME_APPROVE = "attendance:overtime_approve",
    ATTENDANCE_OVERTIME_HR_REVIEW = "attendance:overtime_hr_review",

    // Lương
    PAYROLL_VIEW_SELF = "payroll:view_self",
    PAYROLL_VIEW_ALL = "payroll:view_all",
    PAYROLL_CALCULATE = "payroll:calculate",
    PAYROLL_APPROVE = "payroll:approve",
    PAYROLL_FORMULA_MANAGE = "payroll:formula_manage",
    PAYROLL_SEND_PAYSLIP = "payroll:send_payslip",
    PAYROLL_TAX_MANAGE = "payroll:tax_manage",

    // Onboarding / Offboarding
    ONBOARDING_VIEW = "onboarding:view",
    ONBOARDING_MANAGE = "onboarding:manage",
    OFFBOARDING_VIEW = "offboarding:view",
    OFFBOARDING_MANAGE = "offboarding:manage",

    // Tuyển dụng
    RECRUITMENT_VIEW = "recruitment:view",
    RECRUITMENT_MANAGE = "recruitment:manage",
    RECRUITMENT_POST_CREATE = "recruitment:post_create",
    RECRUITMENT_POST_EDIT = "recruitment:post_edit",
    RECRUITMENT_POST_DELETE = "recruitment:post_delete",
    RECRUITMENT_CANDIDATE_VIEW = "recruitment:candidate_view",
    RECRUITMENT_CANDIDATE_CREATE = "recruitment:candidate_create",
    RECRUITMENT_CANDIDATE_EDIT = "recruitment:candidate_edit",
    RECRUITMENT_CANDIDATE_DELETE = "recruitment:candidate_delete",
    RECRUITMENT_INTERVIEW_SCHEDULE = "recruitment:interview_schedule",
    RECRUITMENT_INTERVIEW_MANAGE = "recruitment:interview_manage",
    RECRUITMENT_CANDIDATE_POOL_VIEW = "recruitment:candidate_pool_view",
    RECRUITMENT_REPORT_VIEW = "recruitment:report_view",
    RECRUITMENT_REPORT_EXPORT = "recruitment:report_export",

    // Đào tạo & Hiệu suất
    TRAINING_VIEW_SELF = "training:view_self",
    TRAINING_VIEW_ALL = "training:view_all",
    TRAINING_MANAGE = "training:manage",
    PERFORMANCE_VIEW_SELF = "performance:view_self",
    PERFORMANCE_VIEW_TEAM = "performance:view_team",
    PERFORMANCE_VIEW_ALL = "performance:view_all",
    PERFORMANCE_EVALUATE = "performance:evaluate",

    // Tài sản & Khen thưởng
    ASSET_VIEW_SELF = "asset:view_self",
    ASSET_VIEW_ALL = "asset:view_all",
    ASSET_MANAGE = "asset:manage",
    REWARD_VIEW = "reward:view",
    REWARD_CREATE = "reward:create",
    REWARD_APPROVE = "reward:approve",

    // Báo cáo
    REPORT_VIEW_BASIC = "report:view_basic",
    REPORT_VIEW_ALL = "report:view_all",
    REPORT_EXPORT = "report:export",

    // ESS
    ESS_VIEW = "ess:view",
    ESS_UPDATE_PROFILE = "ess:update_profile",
    ESS_SEND_REQUEST = "ess:send_request",

    // Cài đặt
    SETTINGS_VIEW = "settings:view",
    SETTINGS_ROLES_MANAGE = "settings:roles_manage",
    SETTINGS_AUDIT_LOG = "settings:audit_log",
    SETTINGS_SYSTEM = "settings:system",
}

// ROLE → PERMISSIONS MAPPING
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
    [Role.SUPER_ADMIN]: Object.values(Permission),

    [Role.DIRECTOR]: [
        Permission.DASHBOARD_VIEW,
        Permission.DASHBOARD_VIEW_ALL,
        Permission.ORG_CHART_VIEW,
        Permission.ORG_CHART_EDIT,
        Permission.DEPT_VIEW,
        Permission.POSITION_VIEW_ALL,
        Permission.EMPLOYEE_VIEW_ALL,
        Permission.EMPLOYEE_EXPORT,
        Permission.CONTRACT_VIEW_ALL,
        Permission.CONTRACT_PRINT,
        Permission.LEAVE_VIEW_ALL,
        Permission.LEAVE_APPROVE_ALL,
        Permission.LEAVE_CALENDAR_VIEW,
        Permission.ATTENDANCE_VIEW_ALL,
        Permission.ATTENDANCE_OVERTIME_APPROVE,
        Permission.ATTENDANCE_OVERTIME_HR_REVIEW,
        Permission.PAYROLL_VIEW_ALL,
        Permission.PAYROLL_APPROVE,
        Permission.ONBOARDING_VIEW,
        Permission.OFFBOARDING_VIEW,
        Permission.RECRUITMENT_VIEW,
        Permission.RECRUITMENT_MANAGE,
        Permission.RECRUITMENT_POST_CREATE,
        Permission.RECRUITMENT_POST_EDIT,
        Permission.RECRUITMENT_POST_DELETE,
        Permission.RECRUITMENT_CANDIDATE_VIEW,
        Permission.RECRUITMENT_CANDIDATE_CREATE,
        Permission.RECRUITMENT_CANDIDATE_EDIT,
        Permission.RECRUITMENT_CANDIDATE_DELETE,
        Permission.RECRUITMENT_INTERVIEW_SCHEDULE,
        Permission.RECRUITMENT_INTERVIEW_MANAGE,
        Permission.RECRUITMENT_CANDIDATE_POOL_VIEW,
        Permission.RECRUITMENT_REPORT_VIEW,
        Permission.RECRUITMENT_REPORT_EXPORT,
        Permission.TRAINING_VIEW_ALL,
        Permission.PERFORMANCE_VIEW_ALL,
        Permission.PERFORMANCE_EVALUATE,
        Permission.ASSET_VIEW_ALL,
        Permission.REWARD_VIEW,
        Permission.REWARD_APPROVE,
        Permission.REPORT_VIEW_ALL,
        Permission.REPORT_EXPORT,
        Permission.ESS_VIEW,
        Permission.ESS_UPDATE_PROFILE,
        Permission.ESS_SEND_REQUEST,
        Permission.SETTINGS_VIEW,
        Permission.SETTINGS_AUDIT_LOG,
    ],

    [Role.HR_MANAGER]: [
        Permission.DASHBOARD_VIEW,
        Permission.DASHBOARD_VIEW_ALL,
        Permission.ORG_CHART_VIEW,
        Permission.ORG_CHART_EDIT,
        Permission.DEPT_VIEW,
        Permission.DEPT_CREATE,
        Permission.DEPT_EDIT,
        Permission.POSITION_VIEW_ALL,
        Permission.POSITION_CREATE,
        Permission.POSITION_EDIT,
        Permission.POSITION_DELETE,
        Permission.EMPLOYEE_VIEW_ALL,
        Permission.EMPLOYEE_CREATE,
        Permission.EMPLOYEE_EDIT,
        Permission.EMPLOYEE_DELETE,
        Permission.EMPLOYEE_IMPORT,
        Permission.EMPLOYEE_EXPORT,
        Permission.CONTRACT_VIEW_ALL,
        Permission.CONTRACT_CREATE,
        Permission.CONTRACT_EDIT,
        Permission.CONTRACT_PRINT,
        Permission.CONTRACT_TEMPLATE_MANAGE,
        Permission.LEAVE_VIEW_ALL,
        Permission.LEAVE_CREATE,
        Permission.LEAVE_APPROVE_ALL,
        Permission.LEAVE_POLICY_MANAGE,
        Permission.LEAVE_CALENDAR_VIEW,
        Permission.ATTENDANCE_VIEW_ALL,
        Permission.ATTENDANCE_CHECKIN,
        Permission.ATTENDANCE_EXPLANATION,
        Permission.ATTENDANCE_APPROVE,
        Permission.ATTENDANCE_SHIFT_MANAGE,
        Permission.ATTENDANCE_OVERTIME_APPROVE,
        Permission.ATTENDANCE_OVERTIME_HR_REVIEW,
        Permission.PAYROLL_VIEW_ALL,
        Permission.PAYROLL_CALCULATE,
        Permission.PAYROLL_FORMULA_MANAGE,
        Permission.PAYROLL_SEND_PAYSLIP,
        Permission.PAYROLL_TAX_MANAGE,
        Permission.ONBOARDING_VIEW,
        Permission.ONBOARDING_MANAGE,
        Permission.OFFBOARDING_VIEW,
        Permission.OFFBOARDING_MANAGE,
        Permission.RECRUITMENT_VIEW,
        Permission.RECRUITMENT_MANAGE,
        Permission.RECRUITMENT_POST_CREATE,
        Permission.RECRUITMENT_POST_EDIT,
        Permission.RECRUITMENT_POST_DELETE,
        Permission.RECRUITMENT_CANDIDATE_VIEW,
        Permission.RECRUITMENT_CANDIDATE_CREATE,
        Permission.RECRUITMENT_CANDIDATE_EDIT,
        Permission.RECRUITMENT_CANDIDATE_DELETE,
        Permission.RECRUITMENT_INTERVIEW_SCHEDULE,
        Permission.RECRUITMENT_INTERVIEW_MANAGE,
        Permission.RECRUITMENT_CANDIDATE_POOL_VIEW,
        Permission.RECRUITMENT_REPORT_VIEW,
        Permission.RECRUITMENT_REPORT_EXPORT,
        Permission.TRAINING_VIEW_ALL,
        Permission.TRAINING_MANAGE,
        Permission.PERFORMANCE_VIEW_ALL,
        Permission.PERFORMANCE_EVALUATE,
        Permission.ASSET_VIEW_ALL,
        Permission.ASSET_MANAGE,
        Permission.REWARD_VIEW,
        Permission.REWARD_CREATE,
        Permission.REWARD_APPROVE,
        Permission.REPORT_VIEW_ALL,
        Permission.REPORT_EXPORT,
        Permission.ESS_VIEW,
        Permission.ESS_UPDATE_PROFILE,
        Permission.ESS_SEND_REQUEST,
        Permission.SETTINGS_VIEW,
    ],

    [Role.HR_STAFF]: [
        Permission.DASHBOARD_VIEW,
        Permission.ORG_CHART_VIEW,
        Permission.DEPT_VIEW,
        Permission.POSITION_VIEW_ALL,
        Permission.POSITION_CREATE,
        Permission.POSITION_EDIT,
        Permission.EMPLOYEE_VIEW_ALL,
        Permission.EMPLOYEE_CREATE,
        Permission.EMPLOYEE_EDIT,
        Permission.EMPLOYEE_IMPORT,
        Permission.EMPLOYEE_EXPORT,
        Permission.CONTRACT_VIEW_ALL,
        Permission.CONTRACT_CREATE,
        Permission.CONTRACT_EDIT,
        Permission.CONTRACT_PRINT,
        Permission.LEAVE_VIEW_ALL,
        Permission.LEAVE_CREATE,
        Permission.LEAVE_CALENDAR_VIEW,
        Permission.ATTENDANCE_VIEW_ALL,
        Permission.ATTENDANCE_CHECKIN,
        Permission.ATTENDANCE_EXPLANATION,
        Permission.PAYROLL_VIEW_ALL,
        Permission.PAYROLL_CALCULATE,
        Permission.PAYROLL_SEND_PAYSLIP,
        Permission.ONBOARDING_VIEW,
        Permission.ONBOARDING_MANAGE,
        Permission.OFFBOARDING_VIEW,
        Permission.OFFBOARDING_MANAGE,
        Permission.RECRUITMENT_VIEW,
        Permission.RECRUITMENT_MANAGE,
        Permission.RECRUITMENT_POST_CREATE,
        Permission.RECRUITMENT_POST_EDIT,
        Permission.RECRUITMENT_CANDIDATE_VIEW,
        Permission.RECRUITMENT_CANDIDATE_CREATE,
        Permission.RECRUITMENT_CANDIDATE_EDIT,
        Permission.RECRUITMENT_INTERVIEW_SCHEDULE,
        Permission.RECRUITMENT_CANDIDATE_POOL_VIEW,
        Permission.TRAINING_VIEW_ALL,
        Permission.PERFORMANCE_VIEW_ALL,
        Permission.ASSET_VIEW_ALL,
        Permission.REWARD_VIEW,
        Permission.REWARD_CREATE,
        Permission.REPORT_VIEW_BASIC,
        Permission.ESS_VIEW,
        Permission.ESS_UPDATE_PROFILE,
        Permission.ESS_SEND_REQUEST,
    ],

    [Role.DEPT_MANAGER]: [
        Permission.DASHBOARD_VIEW,
        Permission.ORG_CHART_VIEW,
        Permission.DEPT_VIEW,
        Permission.POSITION_VIEW_ALL,
        Permission.EMPLOYEE_VIEW_SELF,
        Permission.EMPLOYEE_VIEW_TEAM,
        Permission.CONTRACT_VIEW_SELF,
        Permission.LEAVE_VIEW_SELF,
        Permission.LEAVE_VIEW_TEAM,
        Permission.LEAVE_CREATE,
        Permission.LEAVE_APPROVE_TEAM,
        Permission.LEAVE_CALENDAR_VIEW,
        Permission.ATTENDANCE_VIEW_SELF,
        Permission.ATTENDANCE_VIEW_TEAM,
        Permission.ATTENDANCE_CHECKIN,
        Permission.ATTENDANCE_EXPLANATION,
        Permission.ATTENDANCE_APPROVE,
        Permission.ATTENDANCE_OVERTIME_APPROVE,
        Permission.PAYROLL_VIEW_SELF,
        Permission.ONBOARDING_VIEW,
        Permission.OFFBOARDING_VIEW,
        Permission.RECRUITMENT_VIEW,
        Permission.RECRUITMENT_INTERVIEW_SCHEDULE,
        Permission.TRAINING_VIEW_SELF,
        Permission.PERFORMANCE_VIEW_SELF,
        Permission.PERFORMANCE_VIEW_TEAM,
        Permission.PERFORMANCE_EVALUATE,
        Permission.ASSET_VIEW_SELF,
        Permission.REWARD_VIEW,
        Permission.REWARD_CREATE,
        Permission.REPORT_VIEW_BASIC,
        Permission.ESS_VIEW,
        Permission.ESS_UPDATE_PROFILE,
        Permission.ESS_SEND_REQUEST,
    ],

    [Role.TEAM_LEADER]: [
        Permission.DASHBOARD_VIEW,
        Permission.ORG_CHART_VIEW,
        Permission.DEPT_VIEW,
        Permission.POSITION_VIEW_ALL,
        Permission.EMPLOYEE_VIEW_SELF,
        Permission.EMPLOYEE_VIEW_TEAM,
        Permission.CONTRACT_VIEW_SELF,
        Permission.LEAVE_VIEW_SELF,
        Permission.LEAVE_VIEW_TEAM,
        Permission.LEAVE_CREATE,
        Permission.LEAVE_APPROVE_TEAM,
        Permission.LEAVE_CALENDAR_VIEW,
        Permission.ATTENDANCE_VIEW_SELF,
        Permission.ATTENDANCE_VIEW_TEAM,
        Permission.ATTENDANCE_CHECKIN,
        Permission.ATTENDANCE_EXPLANATION,
        Permission.PAYROLL_VIEW_SELF,
        Permission.TRAINING_VIEW_SELF,
        Permission.PERFORMANCE_VIEW_SELF,
        Permission.PERFORMANCE_VIEW_TEAM,
        Permission.PERFORMANCE_EVALUATE,
        Permission.ASSET_VIEW_SELF,
        Permission.REWARD_VIEW,
        Permission.REPORT_VIEW_BASIC,
        Permission.ESS_VIEW,
        Permission.ESS_UPDATE_PROFILE,
        Permission.ESS_SEND_REQUEST,
    ],

    [Role.EMPLOYEE]: [
        Permission.DASHBOARD_VIEW,
        Permission.ORG_CHART_VIEW,
        Permission.DEPT_VIEW,
        Permission.POSITION_VIEW_ALL,
        Permission.EMPLOYEE_VIEW_SELF,
        Permission.CONTRACT_VIEW_SELF,
        Permission.LEAVE_VIEW_SELF,
        Permission.LEAVE_CREATE,
        Permission.LEAVE_CALENDAR_VIEW,
        Permission.ATTENDANCE_VIEW_SELF,
        Permission.ATTENDANCE_CHECKIN,
        Permission.ATTENDANCE_EXPLANATION,
        Permission.PAYROLL_VIEW_SELF,
        Permission.TRAINING_VIEW_SELF,
        Permission.PERFORMANCE_VIEW_SELF,
        Permission.ASSET_VIEW_SELF,
        Permission.REWARD_VIEW,
        Permission.ESS_VIEW,
        Permission.ESS_UPDATE_PROFILE,
        Permission.ESS_SEND_REQUEST,
    ],

    [Role.ACCOUNTANT]: [
        Permission.DASHBOARD_VIEW,
        Permission.ORG_CHART_VIEW,
        Permission.DEPT_VIEW,
        Permission.POSITION_VIEW_ALL,
        Permission.EMPLOYEE_VIEW_SELF,
        Permission.EMPLOYEE_VIEW_ALL,
        Permission.EMPLOYEE_EXPORT,
        Permission.CONTRACT_VIEW_ALL,
        Permission.LEAVE_VIEW_SELF,
        Permission.LEAVE_CREATE,
        Permission.ATTENDANCE_VIEW_SELF,
        Permission.ATTENDANCE_VIEW_ALL,
        Permission.ATTENDANCE_CHECKIN,
        Permission.ATTENDANCE_EXPLANATION,
        Permission.PAYROLL_VIEW_SELF,
        Permission.PAYROLL_VIEW_ALL,
        Permission.PAYROLL_CALCULATE,
        Permission.PAYROLL_FORMULA_MANAGE,
        Permission.PAYROLL_SEND_PAYSLIP,
        Permission.PAYROLL_TAX_MANAGE,
        Permission.REPORT_VIEW_ALL,
        Permission.REPORT_EXPORT,
        Permission.ESS_VIEW,
        Permission.ESS_UPDATE_PROFILE,
        Permission.ESS_SEND_REQUEST,
    ],

    [Role.IT_ADMIN]: [
        Permission.DASHBOARD_VIEW,
        Permission.ORG_CHART_VIEW,
        Permission.DEPT_VIEW,
        Permission.POSITION_VIEW_ALL,
        Permission.EMPLOYEE_VIEW_SELF,
        Permission.CONTRACT_VIEW_SELF,
        Permission.LEAVE_VIEW_SELF,
        Permission.LEAVE_CREATE,
        Permission.ATTENDANCE_VIEW_SELF,
        Permission.ATTENDANCE_CHECKIN,
        Permission.ATTENDANCE_EXPLANATION,
        Permission.PAYROLL_VIEW_SELF,
        Permission.ONBOARDING_VIEW,
        Permission.TRAINING_VIEW_SELF,
        Permission.PERFORMANCE_VIEW_SELF,
        Permission.ASSET_VIEW_ALL,
        Permission.ASSET_MANAGE,
        Permission.ESS_VIEW,
        Permission.ESS_UPDATE_PROFILE,
        Permission.ESS_SEND_REQUEST,
        Permission.SETTINGS_VIEW,
        Permission.SETTINGS_ROLES_MANAGE,
        Permission.SETTINGS_AUDIT_LOG,
        Permission.SETTINGS_SYSTEM,
    ],
};
